[project]
name = "sm"
version = "0.1.0"
description = "Terminal application to list and connect to EC2 instances via AWS Session Manager."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
